// Generated by gencpp from file ratslam_ros/VisualObjet.msg
// DO NOT EDIT!


#ifndef RATSLAM_ROS_MESSAGE_VISUALOBJET_H
#define RATSLAM_ROS_MESSAGE_VISUALOBJET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ratslam_ros
{
template <class ContainerAllocator>
struct VisualObjet_
{
  typedef VisualObjet_<ContainerAllocator> Type;

  VisualObjet_()
    : x(0.0)
    , y(0.0)
    , label(0)  {
    }
  VisualObjet_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , label(0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef uint8_t _label_type;
  _label_type label;





  typedef boost::shared_ptr< ::ratslam_ros::VisualObjet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ratslam_ros::VisualObjet_<ContainerAllocator> const> ConstPtr;

}; // struct VisualObjet_

typedef ::ratslam_ros::VisualObjet_<std::allocator<void> > VisualObjet;

typedef boost::shared_ptr< ::ratslam_ros::VisualObjet > VisualObjetPtr;
typedef boost::shared_ptr< ::ratslam_ros::VisualObjet const> VisualObjetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ratslam_ros::VisualObjet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ratslam_ros::VisualObjet_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ratslam_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ratslam_ros': ['/home/younes/eclipse-workspace/Hamburg_Lim/src/ratslam_python/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ratslam_ros::VisualObjet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ratslam_ros::VisualObjet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ratslam_ros::VisualObjet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ratslam_ros::VisualObjet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ratslam_ros::VisualObjet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ratslam_ros::VisualObjet_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ratslam_ros::VisualObjet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "817923b48e2ccfeef3b9d7bf797a5e39";
  }

  static const char* value(const ::ratslam_ros::VisualObjet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x817923b48e2ccfeeULL;
  static const uint64_t static_value2 = 0xf3b9d7bf797a5e39ULL;
};

template<class ContainerAllocator>
struct DataType< ::ratslam_ros::VisualObjet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ratslam_ros/VisualObjet";
  }

  static const char* value(const ::ratslam_ros::VisualObjet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ratslam_ros::VisualObjet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
uint8 label\n\
";
  }

  static const char* value(const ::ratslam_ros::VisualObjet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ratslam_ros::VisualObjet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisualObjet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ratslam_ros::VisualObjet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ratslam_ros::VisualObjet_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "label: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.label);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RATSLAM_ROS_MESSAGE_VISUALOBJET_H
